; Firmware del laboratorio. Compilar/subir:  pio run -e ctrl-1 -t upload
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ---- ESP32 maestras (cada una controla UN contenedor) ----
[ctrl_common]
build_src_filter = -<*> +<ctrl/>

[env:ctrl-1]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-1\" -DCMD_PORT=5001
[env:ctrl-2]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-2\" -DCMD_PORT=5002
[env:ctrl-3]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-3\" -DCMD_PORT=5003
[env:ctrl-nao]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-nao\" -DCMD_PORT=5011
[env:ctrl-spot]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-spot\" -DCMD_PORT=5012
[env:ctrl-pepper]
extends = ctrl_common
build_flags = -DDEVICE_ID=\"ctrl-pepper\" -DCMD_PORT=5013

; ---- ESP32 esclava: LEDs de estado ----
[env:led-monitor]
build_src_filter = -<*> +<led_monitor/>
lib_deps = knolleary/PubSubClient@^2.8
